name: .NET Core Build

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build WebRTC Server
      run: dotnet build WebRTCSignalServer/WebRTCSignalServer.csproj --configuration Release --no-restore

    - name: Build Windows Client
      run: dotnet build WebRTCWindowsClient/WebRTCWindowsClient.csproj --configuration Release --no-restore
